export const FETCH_USER_REQUEST = 'FETCH_USER_REQUEST'
export const FETCH_USER_ERROR = 'FETCH_USER_ERROR'

export const FETCH_USER_REGISTER_SUCCESS = 'FETCH_USER_REGISTER_SUCCESS'
export const FETCH_USER_SIGN_IN_SUCCESS = 'FETCH_USER_SIGN_IN_SUCCESS'
export const FETCH_USER_SIGN_OUT_SUCCESS = 'FETCH_USER_SIGN_OUT_SUCCESS'
export const FETCH_USER_UPDATE_SUCCESS = 'FETCH_USER_UPDATE_SUCCESS'

export const FETCH_POST_WISHLIST_SUCCESS = "FETCH_POST_WISHLIST_SUCCESS" 
export const FETCH_UPDATE_WISHLIST_SUCCESS = "FETCH_UPDATE_WISHLIST_SUCCESS"
export const FETCH_DELETE_WISHLIST_SUCCESS = "FETCH_DELETE_WISHLIST_SUCCESS"

export const FETCH_UPDATE_CART_SUCCESS = "FETCH_UPDATE_CART_SUCCESS"
