export const FETCH_USER_REQUEST = 'FETCH_USER_REQUEST'
export const FETCH_USER_ERROR = 'FETCH_USER_ERROR'

export const FETCH_USER_REGISTER_SUCCESS = 'FETCH_USER_REGISTER_SUCCESS'
export const FETCH_USER_SIGN_IN_SUCCESS = 'FETCH_USER_SIGN_IN_SUCCESS'
export const FETCH_USER_SIGN_OUT_SUCCESS = 'FETCH_USER_SIGN_OUT_SUCCESS'
export const FETCH_USER_UPDATE_SUCCESS = 'FETCH_USER_UPDATE_SUCCESS'

export const FETCH_POST_WISHLIST_SUCCESS = "FETCH_POST_WISHLIST_SUCCESS"
export const FETCH_UPDATE_WISHLIST_SUCCESS = "FETCH_UPDATE_WISHLIST_SUCCESS"
export const FETCH_DELETE_WISHLIST_SUCCESS = "FETCH_DELETE_WISHLIST_SUCCESS"

export const FETCH_UPDATE_CART_SUCCESS = "FETCH_UPDATE_CART_SUCCESS"

export const FETCH_UPDATE_FAVORITE_SUCCESS = "FETCH_CREATE_FAVORITE_SUCCESS"

export const FETCH_POST_ORDER_SUCCESS = "FETCH_POST_ORDER_SUCCESS"
export const FETCH_UPDATE_ORDER_SUCCESS = "FETCH_UPDATE_ORDER_SUCCESS"
export const FETCH_DELETE_ORDER_SUCCESS = "FETCH_DELETE_ORDER_SUCCESS"

export const CHANGE_COOKIES_CONSENT = "CHANGE_COOKIES_CONSENT"

export const END_OF_LOADING = "END_OF_LOADING"